---
- name: Add Erlang YUM repository
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash
  args:
    warn: no

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

- name: Add packagecloud GPG key.
  rpm_key:
    key: "https://packagecloud.io/gpg.key"
    state: present

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
