---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199 and
# https://github.com/geerlingguy/ansible-role-java/issues/64
- name: setup-Debian | Ensure 'man' directory exists.
  ansible.builtin.file:  # noqa 208
    path: /usr/share/man/man1
    state: directory
    mode: 0755
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 18

- name: setup-Debian | Ensure erlang is installed.
  ansible.builtin.package:
    name: erlang
    state: present

- name: setup-Debian | Download RabbitMQ package.
  ansible.builtin.get_url:
    url: "{{ rabbitmq_deb_url }}"
    dest: "/tmp/{{ rabbitmq_deb }}"
    mode: 0755

- name: setup-Debian | Ensure RabbitMQ is installed.
  ansible.builtin.apt:
    deb: "/tmp/{{ rabbitmq_deb }}"
    state: present
